# Terminal
cask "ghostty"
brew "starship"

# Shell plugins
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Editors
# brew "neovim"
cask "visual-studio-code"

# Dev
brew "git"
brew "gh"
cask "docker-desktop"
cask "bruno"

# Apps
cask "google-chrome"
cask "1password"
cask "notion"
cask "raycast"
